In [1]:
import numpy as np

In [12]:
np.c_[np.ones((X.shape[0], 1)), X]

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])

In [21]:
class LinearRegression:

    def __init__(self):
        self.weights = None

    def fit(self, X, y):

        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        
        self.weights = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

        
    def predict(self, X):

        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        return X_b.dot(self.weights)

In [22]:
X = np.array([[1], [2], [3], [4], [5]])  # Feature (input)
y = np.array([3, 7, 9, 11, 13])  


lr = LinearRegression()
lr.fit(X, y)
lr.predict(X)

array([ 3.8,  6.2,  8.6, 11. , 13.4])

### Gradient Descent
----

In [25]:
class LinearRegression2:

    def __init__(self, iterations=10, lr=0.001):

        self.iterations = 10
        self.lr = lr
        self.weights = None

    def fit(self, X, y):

        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        self.weights = np.zeros(X_b.shape[1])

        for _ in range(self.iterations):

            predictions = X_b.dot(self.weights)
            error = predictions - y

            # current gradients
            gradients = 2/(X.shape[0]) * (X_b.T.dot(error))

            # update weights
            self.weights -= self.lr * gradients


    def predict(self, X):

        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        return self.weights.dot(X_b)

In [26]:

X = np.array([[1], [2], [3], [4], [5]])  # Feature (input)
y = np.array([3, 7, 9, 11, 13])  # Target (output)

model = LinearRegression2()
model.fit(X, y)
predictions = lr.predict(X)

In [27]:
predictions

array([ 3.8,  6.2,  8.6, 11. , 13.4])