In [1]:
import numpy as np

In [2]:
X = np.array([[1, 3, 2], [2, 3, 2.2]])
np.ones(len(X))

np.c_[np.ones((X.shape[0], 1)), X]

array([[1. , 1. , 3. , 2. ],
       [1. , 2. , 3. , 2.2]])

In [3]:
X

array([[1. , 3. , 2. ],
       [2. , 3. , 2.2]])

In [4]:
np.c_[np.ones((X.shape[0], 1)), X]

array([[1. , 1. , 3. , 2. ],
       [1. , 2. , 3. , 2.2]])

In [5]:
class LinearRegression:

    def __init__(self):
        self.weights = None

    def fit(self, X, y):

        # this will be new X; adding 1 for the bias term
        X_b = np.c_[np.ones((X.shape[0], 1)), X]

        self.weights = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)


    def predict(self, X):
        
        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        return X_b.dot(self.weights)

X = np.array([[1], [2], [3], [4], [5]])  # Feature (input)
y = np.array([3, 7, 9, 11, 13])  

lr = LinearRegression()    
lr.fit(X, y)
predictions = lr.predict(X)

In [6]:
predictions

array([ 3.8,  6.2,  8.6, 11. , 13.4])

In [7]:
print("Predictions:", predictions)
print("Weights:", lr.weights)

Predictions: [ 3.8  6.2  8.6 11.  13.4]
Weights: [1.4 2.4]


In [20]:
##

class LinearRegression2:

    def __init__(self, iterations=10, learning_rate=0.001):

        self.weights = None
        self.iterations = iterations
        self.learning_rate = learning_rate

    
    def fit(self, X, y):

        X_b = np.c_[np.ones((X.shape[0], 1)), X]
        
        self.weights = np.zeros(X_b.shape[1])
        for _ in range(self.iterations):

            predictions = X_b.dot(self.weights)
            error = predictions - y
            
            # 2/m (X * error)
            gradients = (2 / X_b.shape[0]) * X_b.T.dot(error)

            # update gradients
            self.weights = self.weights - (self.learning_rate * gradients)


    def predict(self, X):

        X_b = np.c_[np.ones(X.shape[0], 1), X]
        return X_b.dot(self.weights)

In [21]:
# Sample data
X = np.array([[1], [2], [3], [4], [5]])  # Feature (input)
y = np.array([3, 7, 9, 11, 13])  # Target (output)

model = LinearRegression2()
model.fit(X, y)
predictions = lr.predict(X)

In [22]:
predictions

array([ 3.8,  6.2,  8.6, 11. , 13.4])